"use client";

import React, { createContext, useContext, useState, useEffect } from "react";
import { Cart, CartItem } from "@/types/cart";
import { useAuth } from "./useAuth";
import { getCookie, getCsrfHeader } from "@/utils/cookie";

const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000";

interface SystemSettings {
  tax_rate: number;
  shipping_limit: number;
  shipping_cost: number;
}

interface CartContextType {
  cart: Cart | null;
  itemsCount: number;
  subtotal: number;
  loading: boolean;
  settings: SystemSettings;
  isSidebarOpen: boolean;
  setSidebarOpen: (open: boolean) => void;
  addToCart: (productId: number, quantity?: number) => Promise<void>;
  updateQuantity: (productId: number, quantity: number) => Promise<void>;
  removeFromCart: (productId: number) => Promise<void>;
  clearCart: () => void;
  refreshSettings: () => Promise<void>;
  validateCouponOnServer: (code: string, orderAmount: number) => Promise<{ code: string; type: string; value: number }>;
}

const CartContext = createContext<CartContextType | undefined>(undefined);

export const CartProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [cart, setCart] = useState<Cart | null>(null);
  const [sessionToken, setSessionToken] = useState<string | null>(null);
  const [isTokenLoaded, setIsTokenLoaded] = useState<boolean>(false);
  const [loading, setLoading] = useState<boolean>(true);
  const [isSidebarOpen, setSidebarOpen] = useState<boolean>(false);
  const { user, loading: authLoading } = useAuth();
  // Defaults mirror the server's (no GST, no shipping) so totals don't flicker
  // to a different number between first paint and /api/settings resolving.
  const [settings, setSettings] = useState<SystemSettings>({
    tax_rate: 0,
    shipping_limit: 0,
    shipping_cost: 0
  });

  // Initialize session token from localStorage
  useEffect(() => {
    if (typeof window !== "undefined") {
      const savedToken = localStorage.getItem("sessionToken");
      if (savedToken) {
        setTimeout(() => setSessionToken(savedToken), 0);
      }
      setTimeout(() => setIsTokenLoaded(true), 0);
    }
  }, []);

  const fetchSettings = async () => {
    try {
      const res = await fetch(`${API_URL}/api/settings`, { cache: "no-store" });
      if (res.ok) {
        const data = await res.json();
        setSettings(data);
      }
    } catch (err) {
      console.error("Failed to fetch settings:", err);
    }
  };

  // Fetch settings on mount
  useEffect(() => {
    setTimeout(() => {
      fetchSettings();
    }, 0);
  }, []);

  // Fetch the cart once the session token has been read from localStorage AND
  // auth has settled.
  //
  // Waiting on `authLoading` matters: this effect used to run while `user` was
  // still null for a signed-in shopper, so the first request went out as
  // anonymous (against a stale `sessionToken`, if one was left in
  // localStorage) and a second went out once `user` arrived. Neither request
  // was cancelled, so whichever finished last won — land them out of order and
  // a signed-in shopper saw the empty anonymous cart, which on /checkout reads
  // as "Nothing to Checkout" until they reload the page.
  useEffect(() => {
    if (!isTokenLoaded || authLoading) return;

    // Keeps a response from a superseded run from overwriting a newer one.
    let active = true;

    const fetchCart = async () => {
      try {
        let url = `${API_URL}/api/cart`;
        if (!user && sessionToken) {
          url += `?sessionToken=${sessionToken}`;
        }
        
        const tokenCookie = getCookie("token");
        const headers: HeadersInit = {};
        if (tokenCookie) {
          headers["Authorization"] = `Bearer ${tokenCookie}`;
        }
        if (!user && sessionToken) {
          headers["x-session-token"] = sessionToken;
        }

        const response = await fetch(url, {
          cache: "no-store",
          credentials: "include",
          headers
        });

        if (response.ok) {
          const data: Cart = await response.json();
          if (!active) return;
          setCart(data);

          // Store token if generated by the backend and not logged in
          if (!user && !sessionToken && data.sessionToken) {
            localStorage.setItem("sessionToken", data.sessionToken);
            setSessionToken(data.sessionToken);
          }
        }
      } catch (error) {
        console.error("Failed to load cart:", error);
      } finally {
        if (active) setLoading(false);
      }
    };

    fetchCart();

    return () => {
      active = false;
    };
  }, [sessionToken, isTokenLoaded, user, authLoading]);

  const addToCart = async (productId: number, quantity: number = 1) => {
    let token = sessionToken;
    if (!user && !token) {
      token = typeof window !== "undefined" ? window.crypto?.randomUUID() || Math.random().toString(36).substring(2) : "";
      if (typeof window !== "undefined" && token) {
        localStorage.setItem("sessionToken", token);
        setSessionToken(token);
      }
    }

    try {
      const tokenCookie = getCookie("token");
      const headers: HeadersInit = {
        "Content-Type": "application/json",
        ...getCsrfHeader(),
      };
      if (tokenCookie) {
        headers["Authorization"] = `Bearer ${tokenCookie}`;
      }
      if (!user && token) {
        headers["x-session-token"] = token;
      }

      const response = await fetch(`${API_URL}/api/cart/items`, {
        method: "POST",
        credentials: "include",
        headers,
        body: JSON.stringify({ productId, quantity }),
      });

      if (response.ok) {
        const updatedCart = await response.json();
        setCart(updatedCart);
        // Automatically open the sidebar to show the item was added
        setSidebarOpen(true);
      } else {
        console.error("Failed to add item to cart");
      }
    } catch (error) {
      console.error("Error adding item to cart:", error);
    }
  };

  const updateQuantity = async (productId: number, quantity: number) => {
    const token = sessionToken || (typeof window !== "undefined" ? localStorage.getItem("sessionToken") : null);
    if (!user && !token) return;
    try {
      const tokenCookie = getCookie("token");
      const headers: HeadersInit = {
        "Content-Type": "application/json",
        ...getCsrfHeader(),
      };
      if (tokenCookie) {
        headers["Authorization"] = `Bearer ${tokenCookie}`;
      }
      if (!user && token) {
        headers["x-session-token"] = token;
      }

      const response = await fetch(`${API_URL}/api/cart/items`, {
        method: "PUT",
        credentials: "include",
        headers,
        body: JSON.stringify({ productId, quantity }),
      });

      if (response.ok) {
        const updatedCart = await response.json();
        setCart(updatedCart);
      } else {
        console.error("Failed to update quantity");
      }
    } catch (error) {
      console.error("Error updating quantity:", error);
    }
  };

  const removeFromCart = async (productId: number) => {
    const token = sessionToken || (typeof window !== "undefined" ? localStorage.getItem("sessionToken") : null);
    if (!user && !token) return;
    try {
      const tokenCookie = getCookie("token");
      const headers: HeadersInit = { ...getCsrfHeader() };
      if (tokenCookie) {
        headers["Authorization"] = `Bearer ${tokenCookie}`;
      }
      if (!user && token) {
        headers["x-session-token"] = token;
      }

      const response = await fetch(`${API_URL}/api/cart/items/${productId}`, {
        method: "DELETE",
        credentials: "include",
        headers,
      });

      if (response.ok) {
        const updatedCart = await response.json();
        setCart(updatedCart);
      } else {
        console.error("Failed to remove item");
      }
    } catch (error) {
      console.error("Error removing item:", error);
    }
  };

  const validateCouponOnServer = async (code: string, orderAmount: number) => {
    const response = await fetch(`${API_URL}/api/coupons/validate`, {
      method: "POST",
      // requireAuth on the backend needs the HttpOnly auth cookie, which only
      // rides along on a `credentials: "include"` request.
      credentials: "include",
      headers: {
        "Content-Type": "application/json",
        ...getCsrfHeader(),
      },
      body: JSON.stringify({ code, orderAmount })
    });

    if (!response.ok) {
      const errData = await response.json();
      throw new Error(errData.message || "Failed to validate coupon");
    }

    return response.json();
  };

  const clearCart = () => {
    setCart(null);
    if (typeof window !== "undefined") {
      localStorage.removeItem("sessionToken");
      setSessionToken(null);
    }
  };

  // Calculations
  const itemsCount = cart?.items?.reduce((sum, item) => sum + item.quantity, 0) || 0;
  const subtotal = cart?.items?.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0) || 0;

  return (
    <CartContext.Provider
      value={{
        cart,
        itemsCount,
        subtotal,
        loading: loading || !isTokenLoaded || authLoading,
        settings,
        isSidebarOpen,
        setSidebarOpen,
        addToCart,
        updateQuantity,
        removeFromCart,
        clearCart,
        refreshSettings: fetchSettings,
        validateCouponOnServer
      }}
    >
      {children}
    </CartContext.Provider>
  );
};

export const useCart = () => {
  const context = useContext(CartContext);
  if (context === undefined) {
    throw new Error("useCart must be used within a CartProvider");
  }
  return context;
};
